import { inspectorFixtureArtifactKey } from "./inspector-fixture.js";
import type { VisualAction, VisualCaptureTarget, VisualCaseDefinition, VisualViewport } from "./visual-contract.js";

const compact: VisualViewport = { width: 1366, height: 768 };

function componentTarget(componentType: string, label: string): VisualCaptureTarget {
  return { kind: "selector", label, selector: `[data-component-type="${componentType}"]` };
}

function inspectorCase(
  id: string,
  title: string,
  description: string,
  nodeId: string,
  componentType: string,
  stateId: string,
  label: string,
  extraActions: readonly VisualAction[] = [],
  targetSelector?: string,
): VisualCaseDefinition {
  const actions: readonly VisualAction[] = [
    { kind: "waitForText", text: inspectorFixtureArtifactKey, exact: true },
    { kind: "clickButton", name: "Hierarchy", exact: true },
    { kind: "clickSelector", selector: `[data-hierarchy-row][data-node-id="${nodeId}"] button[data-hierarchy-select]` },
    { kind: "waitForSelector", selector: `[data-component-type="${componentType}"]` },
    ...extraActions,
  ];
  return {
    id,
    title,
    description,
    route: `/?artifact=${inspectorFixtureArtifactKey}`,
    viewport: compact,
    actions,
    target: targetSelector ? { kind: "selector", label, selector: targetSelector } : componentTarget(componentType, label),
    workspace: "inspectorFixture",
    componentType,
    stateId,
  };
}

export const customComponentInspectorCases: readonly VisualCaseDefinition[] = [
  inspectorCase(
    "crosshair-default",
    "Crosshair / 默认状态",
    "核对空 Edges 与默认 Punch。",
    "crosshairDefault",
    "Crosshair",
    "default",
    "Crosshair",
  ),
  inspectorCase(
    "crosshair-representative",
    "Crosshair / 四向准星",
    "核对 Scatter、Edges 与 Punch 复合字段。",
    "crosshairRepresentative",
    "Crosshair",
    "four-edges",
    "Crosshair",
  ),
  inspectorCase(
    "virtual-joystick-default",
    "Virtual Joystick / 默认状态",
    "核对 Area、Background、Knob 与默认行为字段。",
    "virtualJoystickDefault",
    "VirtualJoystick",
    "default",
    "Virtual Joystick",
  ),
  inspectorCase(
    "virtual-joystick-representative",
    "Virtual Joystick / 代表配置",
    "核对静态背景、空闲 Knob 可见与 Max Offset Scale。",
    "virtualJoystickRepresentative",
    "VirtualJoystick",
    "representative",
    "Virtual Joystick",
  ),
  inspectorCase(
    "state-root-default",
    "State Root / 默认状态",
    "核对最小状态列表与当前状态。",
    "stateRootDefault",
    "StateRoot",
    "default",
    "State Root",
  ),
  inspectorCase(
    "state-root-representative",
    "State Root / 全类型状态属性",
    "核对 20 种 property element 的复合控件与状态值布局。",
    "stateRootRepresentative",
    "StateRoot",
    "state-elements",
    "State Root",
    [{ kind: "clickTitle", title: "展开状态 selected" }],
  ),
  inspectorCase(
    "state-root-sprite-controls",
    "State Root / Sprite 与下半段控件",
    "核对 Sprite/SNS、Boolean、CanvasGroup、Vector3 与 Font 状态值控件。",
    "stateRootRepresentative",
    "StateRoot",
    "sprite-vector3-font",
    "State Root",
    [
      { kind: "clickTitle", title: "展开状态 selected" },
      {
        kind: "clickSelector",
        selector: '[data-state-name="selected"] [data-ui~="state-root-value-row"]:has([title$=" · USprite"])',
      },
    ],
    '[data-state-name="selected"]',
  ),
  inspectorCase(
    "state-toggle-single",
    "State Toggle / 单选",
    "核对必选单选状态。",
    "stateToggleSingle",
    "StateToggle",
    "single",
    "State Toggle",
  ),
  inspectorCase(
    "state-toggle-multiple",
    "State Toggle / 多选",
    "核对 Multiple Select、Allow Switch Off 与索引选择。",
    "stateToggleMultiple",
    "StateToggle",
    "multiple",
    "State Toggle",
  ),
  inspectorCase(
    "custom-drop-down-default",
    "Custom DropDown / 默认结构",
    "核对 View、Toggle 与 Template 配对引用。",
    "customDropDownDefault",
    "CustomDropDown",
    "default",
    "Custom DropDown",
  ),
  inspectorCase(
    "custom-drop-down-sized",
    "Custom DropDown / 尺寸范围",
    "核对成熟项目使用过的 Min/Max Option View Size。",
    "customDropDownSized",
    "CustomDropDown",
    "sized",
    "Custom DropDown",
  ),
  inspectorCase(
    "custom-drop-down-option",
    "Custom DropDown Option / 结构",
    "核对 Type、Select StateRoot 与 Button 引用。",
    "dropdownOptionTemplate",
    "CustomDropDownOption",
    "representative",
    "Custom DropDown Option",
  ),
  inspectorCase(
    "scroll-rect-ex-default",
    "Scroll Rect Ex / 默认状态",
    "核对 Scroll Rect 基础字段与空 Templates。",
    "layoutSettingsDefault",
    "ScrollRectEx",
    "default",
    "Scroll Rect Ex",
  ),
  inspectorCase(
    "scroll-rect-ex-representative",
    "Scroll Rect Ex / 代表配置",
    "核对 Clamped、Auto Clamped、Empty Target 与 Templates。",
    "layoutSettingsRepresentative",
    "ScrollRectEx",
    "representative",
    "Scroll Rect Ex",
  ),
  inspectorCase(
    "canvas-group-default",
    "Canvas Group / 默认状态",
    "核对 Alpha 与交互字段的默认值。",
    "canvasGroupDefault",
    "CanvasGroup",
    "default",
    "Canvas Group",
  ),
  inspectorCase(
    "canvas-group-representative",
    "Canvas Group / 代表配置",
    "核对 Alpha、交互阻挡与忽略父级分组。",
    "canvasGroupRepresentative",
    "CanvasGroup",
    "representative",
    "Canvas Group",
  ),
];
