import { inspectorFixtureArtifactKey } from "./inspector-fixture.js";
import type { VisualAction, VisualCaptureTarget, VisualCaseDefinition, VisualViewport } from "./visual-contract.js";

const compact: VisualViewport = { width: 1366, height: 768 };

function ready(): VisualAction {
  return { kind: "waitForText", text: inspectorFixtureArtifactKey, exact: true };
}

function componentTarget(componentType: string, label: string): VisualCaptureTarget {
  return { kind: "selector", label, selector: `[data-component-type="${componentType}"]` };
}

function inspectorCase(
  id: string,
  title: string,
  description: string,
  nodeId: string,
  componentType: string,
  stateId: string,
  label: string,
): VisualCaseDefinition {
  return {
    id,
    title,
    description,
    route: `/?artifact=${inspectorFixtureArtifactKey}`,
    viewport: compact,
    actions: [
      ready(),
      { kind: "clickButton", name: "Hierarchy", exact: true },
      { kind: "clickSelector", selector: `button[data-hierarchy-select][title="${nodeId}"]` },
      { kind: "waitForSelector", selector: `[data-component-type="${componentType}"]` },
    ],
    target: componentTarget(componentType, label),
    workspace: "inspectorFixture",
    componentType,
    stateId,
  };
}

export const layoutInspectorCases: readonly VisualCaseDefinition[] = [
  inspectorCase(
    "horizontal-layout-default",
    "Horizontal Layout Group / 默认状态",
    "核对线性布局默认字段。",
    "horizontalLayoutDefault",
    "HorizontalLayoutGroup",
    "default",
    "Horizontal Layout Group",
  ),
  inspectorCase(
    "horizontal-layout-representative",
    "Horizontal Layout Group / 代表配置",
    "核对 Padding、Spacing、Alignment 与子节点尺寸控制。",
    "horizontalLayoutRepresentative",
    "HorizontalLayoutGroup",
    "representative",
    "Horizontal Layout Group",
  ),
  inspectorCase(
    "vertical-layout-default",
    "Vertical Layout Group / 默认状态",
    "核对线性布局默认字段。",
    "verticalLayoutDefault",
    "VerticalLayoutGroup",
    "default",
    "Vertical Layout Group",
  ),
  inspectorCase(
    "vertical-layout-representative",
    "Vertical Layout Group / 代表配置",
    "核对 Padding、Spacing、Alignment 与子节点尺寸控制。",
    "verticalLayoutRepresentative",
    "VerticalLayoutGroup",
    "representative",
    "Vertical Layout Group",
  ),
  inspectorCase(
    "grid-layout-default",
    "Grid Layout Group / 默认状态",
    "核对 Cell Size 与默认 Grid 字段。",
    "gridLayoutDefault",
    "GridLayoutGroup",
    "default",
    "Grid Layout Group",
  ),
  inspectorCase(
    "grid-layout-fixed-columns",
    "Grid Layout Group / Fixed Columns",
    "核对当前高频固定列数条件字段。",
    "gridLayoutFixedColumns",
    "GridLayoutGroup",
    "fixed-columns",
    "Grid Layout Group",
  ),
  inspectorCase(
    "auto-layout-horizontal",
    "Auto Layout Group / Horizontal",
    "核对线性模式字段分支。",
    "autoLayoutHorizontal",
    "AutoLayoutGroup",
    "horizontal",
    "Auto Layout Group",
  ),
  inspectorCase(
    "auto-layout-grid-auto",
    "Auto Layout Group / Auto Grid",
    "核对自动网格隐藏无效的 Rows 与 Columns。",
    "autoLayoutGridAuto",
    "AutoLayoutGroup",
    "grid-auto",
    "Auto Layout Group",
  ),
  inspectorCase(
    "auto-layout-grid-manual",
    "Auto Layout Group / Manual Grid",
    "核对 Horizontal 起始轴只显示 Columns。",
    "autoLayoutGridManual",
    "AutoLayoutGroup",
    "grid-manual",
    "Auto Layout Group",
  ),
  inspectorCase(
    "content-size-fitter-default",
    "Content Size Fitter / 默认状态",
    "核对两轴 Fit Mode。",
    "contentSizeFitterDefault",
    "ContentSizeFitter",
    "default",
    "Content Size Fitter",
  ),
  inspectorCase(
    "content-size-fitter-preferred",
    "Content Size Fitter / Preferred Size",
    "核对当前项目高频 Preferred Size。",
    "contentSizeFitterPreferred",
    "ContentSizeFitter",
    "preferred-size",
    "Content Size Fitter",
  ),
  inspectorCase(
    "layout-element-default",
    "Layout Element / 默认状态",
    "核对 Optional Number 未启用状态。",
    "layoutElementDefault",
    "LayoutElement",
    "default",
    "Layout Element",
  ),
  inspectorCase(
    "layout-element-representative",
    "Layout Element / 代表配置",
    "核对 Preferred 与 Flexible 字段。",
    "layoutElementRepresentative",
    "LayoutElement",
    "representative",
    "Layout Element",
  ),
  inspectorCase(
    "layout-element-ignored",
    "Layout Element / Ignore Layout",
    "核对 Ignore Layout 条件收起。",
    "layoutElementIgnored",
    "LayoutElement",
    "ignore-layout",
    "Layout Element",
  ),
  inspectorCase(
    "aspect-ratio-default",
    "Aspect Ratio Fitter / Source Default",
    "核对 Source 的有效 Aspect Mode 与 Ratio。",
    "aspectRatioDefault",
    "AspectRatioFitter",
    "source-default",
    "Aspect Ratio Fitter",
  ),
  inspectorCase(
    "aspect-ratio-envelope",
    "Aspect Ratio Fitter / Envelope Parent",
    "核对当前项目 16:9 背景配置。",
    "aspectRatioEnvelope",
    "AspectRatioFitter",
    "envelope-parent",
    "Aspect Ratio Fitter",
  ),
  inspectorCase(
    "safe-area-default",
    "Safe Area / Source Default",
    "核对参考方向、边缘与对齐字段。",
    "safeAreaDefault",
    "SafeArea",
    "source-default",
    "Safe Area",
  ),
  inspectorCase(
    "layout-settings-default",
    "Layout Settings / 默认状态",
    "核对 Scroll Rect Ex 布局参数默认值。",
    "layoutSettingsDefault",
    "LayoutSettings",
    "default",
    "Layout Settings",
  ),
  inspectorCase(
    "layout-settings-representative",
    "Layout Settings / 代表配置",
    "核对高频 Spacing 与当前 Padding。",
    "layoutSettingsRepresentative",
    "LayoutSettings",
    "representative",
    "Layout Settings",
  ),
];
