import { customComponentInspectorCases } from "./custom-component-inspector-cases.js";
import { inspectorFixtureArtifactKey, inspectorTextOverrideArtifactKey } from "./inspector-fixture.js";
import { interactionInspectorCases } from "./interaction-inspector-cases.js";
import { layoutInspectorCases } from "./layout-inspector-cases.js";
import { resourceStructureInspectorCases } from "./resource-structure-inspector-cases.js";
import type { VisualAction, VisualCaptureTarget, VisualCaseDefinition, VisualViewport } from "./visual-contract.js";

const wide: VisualViewport = { width: 1600, height: 900 };
const compact: VisualViewport = { width: 1366, height: 768 };
const page: VisualCaptureTarget = { kind: "page", label: "完整编辑器" };
const hierarchyPanel: VisualCaptureTarget = { kind: "selector", label: "Hierarchy 面板", selector: '[data-ui="tree-panel"]' };
const inspectorPanel: VisualCaptureTarget = { kind: "selector", label: "Inspector 面板", selector: '[data-ui~="inspector-panel"]' };

function componentTarget(componentType: string, label: string): VisualCaptureTarget {
  return { kind: "selector", label, selector: `[data-component-type="${componentType}"]` };
}

function ready(documentName: string): VisualAction {
  return { kind: "waitForText", text: documentName, exact: true };
}

const prefabRefSelection: readonly VisualAction[] = [
  ready("SettingsCanvas"),
  { kind: "clickButton", name: "Hierarchy", exact: true },
  { kind: "clickSelector", selector: 'button[title*="SettingsQualityOptionFragment/titleText"]', first: true },
];

function inspectorFixtureSelection(nodeId: string, componentType: string): readonly VisualAction[] {
  return [
    ready(inspectorFixtureArtifactKey),
    { kind: "clickButton", name: "Hierarchy", exact: true },
    { kind: "clickSelector", selector: `button[data-hierarchy-select][title="${nodeId}"]` },
    { kind: "waitForSelector", selector: `[data-component-type="${componentType}"]` },
  ];
}

function inspectorOverrideSelection(nodeId: string, componentType: string): readonly VisualAction[] {
  return [
    ready(inspectorTextOverrideArtifactKey),
    { kind: "clickButton", name: "Hierarchy", exact: true },
    { kind: "clickSelector", selector: `button[data-hierarchy-select][title*="InspectorTextWidget/${nodeId}"]` },
    { kind: "waitForSelector", selector: `[data-component-type="${componentType}"]` },
  ];
}

export const visualCases: readonly VisualCaseDefinition[] = [
  {
    id: "canvas-preview-wide",
    title: "Canvas / 预览 / 宽屏",
    description: "复杂 Canvas、组合 Widget、主画布与完整编辑器布局。",
    route: "/?artifact=BackpackCanvas",
    viewport: wide,
    actions: [ready("BackpackCanvas")],
    target: page,
  },
  {
    id: "canvas-unity-baseline-wide",
    title: "Canvas / Unity 基线 / 宽屏",
    description: "同一 Canvas 在不应用 Reference evidence 时的 Web baseline。",
    route: "/?artifact=BackpackCanvas",
    viewport: wide,
    actions: [ready("BackpackCanvas"), { kind: "clickButton", name: "Unity 基线", exact: true }],
    target: page,
  },
  {
    id: "canvas-preview-compact",
    title: "Canvas / 预览 / 紧凑窗口",
    description: "检查较窄编辑器窗口下的面板、画布和工具栏布局。",
    route: "/?artifact=BackpackCanvas",
    viewport: compact,
    actions: [ready("BackpackCanvas")],
    target: page,
  },
  {
    id: "widget-edit-preview-wide",
    title: "Widget / 编辑预览",
    description: "默认 Reference 的编辑预览画面与 Reference Inspector。",
    route: "/?artifact=SquadStatusItemWidget",
    viewport: wide,
    actions: [ready("SquadStatusItemWidget"), { kind: "clickButton", name: "编辑预览", exact: true }],
    target: page,
  },
  {
    id: "widget-state-overview-wide",
    title: "Widget / StateRoot 总览",
    description: "Widget 多组 StateRoot 的卡片布局、状态标记和 Inspector。",
    route: "/?artifact=SquadStatusItemWidget",
    viewport: wide,
    actions: [
      ready("SquadStatusItemWidget"),
      { kind: "clickButton", name: "Unity 基线", exact: true },
      { kind: "clickTitle", title: "展开所有 StateRoot 状态" },
      { kind: "waitForSelector", selector: '[aria-label="StateRoot 状态总览"]' },
    ],
    target: page,
  },
  {
    id: "reference-preview-wide",
    title: "Reference / 预览",
    description: "命名 Reference 的组合内容与评审状态。",
    route: "/?reference=CombatReadyMixedTeamReference",
    viewport: wide,
    actions: [ready("CombatReadyMixedTeamReference")],
    target: page,
  },
  {
    id: "reference-edit-preview-wide",
    title: "Reference / 编辑预览",
    description: "命名 Reference 的证据编辑器与集合数据 Inspector。",
    route: "/?reference=CombatReadyMixedTeamReference",
    viewport: wide,
    actions: [ready("CombatReadyMixedTeamReference"), { kind: "clickButton", name: "编辑预览", exact: true }],
    target: page,
  },
  {
    id: "prefab-ref-hierarchy-inspector-compact",
    title: "PrefabRef / Hierarchy + Inspector",
    description: "PrefabRef use-site 深层节点选择及完整编辑关系。",
    route: "/?artifact=SettingsCanvas",
    viewport: compact,
    actions: prefabRefSelection,
    target: page,
  },
  {
    id: "prefab-ref-hierarchy-panel",
    title: "PrefabRef / Hierarchy 定点",
    description: "Hierarchy 展开、节点身份、override 标记与选中状态。",
    route: "/?artifact=SettingsCanvas",
    viewport: compact,
    actions: prefabRefSelection,
    target: hierarchyPanel,
  },
  {
    id: "prefab-ref-inspector-panel",
    title: "PrefabRef / Inspector 定点",
    description: "继承 Text 节点的 Rect Transform、TMP Text 与来源反馈。",
    route: "/?artifact=SettingsCanvas",
    viewport: compact,
    actions: prefabRefSelection,
    target: inspectorPanel,
  },
  {
    id: "tmp-text-default",
    title: "TMP Text / 默认状态",
    description: "只截取 TMP Text Component，核对默认字段、控件和信息密度。",
    route: `/?artifact=${inspectorFixtureArtifactKey}`,
    viewport: compact,
    actions: inspectorFixtureSelection("tmpTextDefault", "Text"),
    target: componentTarget("Text", "TMP Text"),
    workspace: "inspectorFixture",
    componentType: "Text",
    stateId: "default",
  },
  {
    id: "tmp-text-representative",
    title: "TMP Text / 代表配置",
    description: "覆盖项目常用文本、描边、颜色、对齐、溢出、间距和边距字段。",
    route: `/?artifact=${inspectorFixtureArtifactKey}`,
    viewport: compact,
    actions: inspectorFixtureSelection("tmpTextRepresentative", "Text"),
    target: componentTarget("Text", "TMP Text"),
    workspace: "inspectorFixture",
    componentType: "Text",
    stateId: "representative",
  },
  {
    id: "tmp-text-long-content",
    title: "TMP Text / 长文本",
    description: "检查 multiline、自动换行、截断、间距和边距的组合展示。",
    route: `/?artifact=${inspectorFixtureArtifactKey}`,
    viewport: compact,
    actions: inspectorFixtureSelection("tmpTextLongContent", "Text"),
    target: componentTarget("Text", "TMP Text"),
    workspace: "inspectorFixture",
    componentType: "Text",
    stateId: "long-content",
  },
  {
    id: "tmp-text-use-site-override",
    title: "TMP Text / Use-site Override",
    description: "继承 TMP Text 的字段来源、当前层覆写和重置入口。",
    route: `/?artifact=${inspectorTextOverrideArtifactKey}`,
    viewport: compact,
    actions: inspectorOverrideSelection("inheritedText", "Text"),
    target: componentTarget("Text", "TMP Text"),
    workspace: "inspectorFixture",
    componentType: "Text",
    stateId: "use-site-override",
  },
  {
    id: "image-default",
    title: "Image / 默认状态",
    description: "只截取 Image Component，核对无 Sprite 时的常驻字段。",
    route: `/?artifact=${inspectorFixtureArtifactKey}`,
    viewport: compact,
    actions: inspectorFixtureSelection("imageDefault", "Image"),
    target: componentTarget("Image", "Image"),
    workspace: "inspectorFixture",
    componentType: "Image",
    stateId: "default",
  },
  {
    id: "image-simple",
    title: "Image / Simple",
    description: "核对项目高频 Sprite、Color、Raycast 与 Simple 条件字段。",
    route: `/?artifact=${inspectorFixtureArtifactKey}`,
    viewport: compact,
    actions: inspectorFixtureSelection("imageSimple", "Image"),
    target: componentTarget("Image", "Image"),
    workspace: "inspectorFixture",
    componentType: "Image",
    stateId: "simple",
  },
  {
    id: "image-sliced",
    title: "Image / Sliced",
    description: "核对九宫格 Sprite 的 Fill Center 与 Pixels Per Unit Multiplier。",
    route: `/?artifact=${inspectorFixtureArtifactKey}`,
    viewport: compact,
    actions: inspectorFixtureSelection("imageSliced", "Image"),
    target: componentTarget("Image", "Image"),
    workspace: "inspectorFixture",
    componentType: "Image",
    stateId: "sliced",
  },
  {
    id: "image-filled",
    title: "Image / Filled",
    description: "核对 Fill Method、Origin、Amount、Clockwise 与 Preserve Aspect。",
    route: `/?artifact=${inspectorFixtureArtifactKey}`,
    viewport: compact,
    actions: inspectorFixtureSelection("imageFilled", "Image"),
    target: componentTarget("Image", "Image"),
    workspace: "inspectorFixture",
    componentType: "Image",
    stateId: "filled",
  },
  {
    id: "image-use-site-override",
    title: "Image / Use-site Override",
    description: "核对继承 Image 的字段来源、当前层覆写和重置入口。",
    route: `/?artifact=${inspectorTextOverrideArtifactKey}`,
    viewport: compact,
    actions: inspectorOverrideSelection("inheritedImage", "Image"),
    target: componentTarget("Image", "Image"),
    workspace: "inspectorFixture",
    componentType: "Image",
    stateId: "use-site-override",
  },
  {
    id: "rounded-rect-default",
    title: "Rounded Rect / 默认状态",
    description: "核对 Rounded Rect 的默认字段与密度。",
    route: `/?artifact=${inspectorFixtureArtifactKey}`,
    viewport: compact,
    actions: inspectorFixtureSelection("roundedRectDefault", "RoundedRect"),
    target: componentTarget("RoundedRect", "Rounded Rect"),
    workspace: "inspectorFixture",
    componentType: "RoundedRect",
    stateId: "default",
  },
  {
    id: "rounded-rect-representative",
    title: "Rounded Rect / 代表配置",
    description: "核对高频 Color、Corner Radii 与 Raycast Target。",
    route: `/?artifact=${inspectorFixtureArtifactKey}`,
    viewport: compact,
    actions: inspectorFixtureSelection("roundedRectRepresentative", "RoundedRect"),
    target: componentTarget("RoundedRect", "Rounded Rect"),
    workspace: "inspectorFixture",
    componentType: "RoundedRect",
    stateId: "representative",
  },
  {
    id: "rounded-rect-use-site-override",
    title: "Rounded Rect / Use-site Override",
    description: "核对继承 Rounded Rect 的颜色与圆角覆写。",
    route: `/?artifact=${inspectorTextOverrideArtifactKey}`,
    viewport: compact,
    actions: inspectorOverrideSelection("inheritedRoundedRect", "RoundedRect"),
    target: componentTarget("RoundedRect", "Rounded Rect"),
    workspace: "inspectorFixture",
    componentType: "RoundedRect",
    stateId: "use-site-override",
  },
  {
    id: "mask-default",
    title: "Mask / 默认状态",
    description: "核对 Mask 在同节点 Graphic 上的默认字段。",
    route: `/?artifact=${inspectorFixtureArtifactKey}`,
    viewport: compact,
    actions: inspectorFixtureSelection("maskDefault", "Mask"),
    target: componentTarget("Mask", "Mask"),
    workspace: "inspectorFixture",
    componentType: "Mask",
    stateId: "default",
  },
  {
    id: "mask-hidden-graphic",
    title: "Mask / 隐藏 Graphic",
    description: "核对 Show Mask Graphic 关闭状态。",
    route: `/?artifact=${inspectorFixtureArtifactKey}`,
    viewport: compact,
    actions: inspectorFixtureSelection("maskHiddenGraphic", "Mask"),
    target: componentTarget("Mask", "Mask"),
    workspace: "inspectorFixture",
    componentType: "Mask",
    stateId: "hidden-graphic",
  },
  {
    id: "rect-mask-2d-default",
    title: "Rect Mask 2D / 默认状态",
    description: "核对当前项目高频使用的空配置状态。",
    route: `/?artifact=${inspectorFixtureArtifactKey}`,
    viewport: compact,
    actions: inspectorFixtureSelection("rectMaskDefault", "RectMask2D"),
    target: componentTarget("RectMask2D", "Rect Mask 2D"),
    workspace: "inspectorFixture",
    componentType: "RectMask2D",
    stateId: "default",
  },
  {
    id: "rect-mask-2d-representative",
    title: "Rect Mask 2D / Padding 与 Softness",
    description: "核对旧项目有实际使用的 Padding 与 Softness。",
    route: `/?artifact=${inspectorFixtureArtifactKey}`,
    viewport: compact,
    actions: inspectorFixtureSelection("rectMaskRepresentative", "RectMask2D"),
    target: componentTarget("RectMask2D", "Rect Mask 2D"),
    workspace: "inspectorFixture",
    componentType: "RectMask2D",
    stateId: "representative",
  },
  {
    id: "rect-mask-2d-use-site-override",
    title: "Rect Mask 2D / Use-site Override",
    description: "核对继承 Rect Mask 2D 的 Padding 覆写。",
    route: `/?artifact=${inspectorTextOverrideArtifactKey}`,
    viewport: compact,
    actions: inspectorOverrideSelection("inheritedRectMask", "RectMask2D"),
    target: componentTarget("RectMask2D", "Rect Mask 2D"),
    workspace: "inspectorFixture",
    componentType: "RectMask2D",
    stateId: "use-site-override",
  },
  {
    id: "shape-soft-mask-rect",
    title: "Shape Soft Mask / Rect",
    description: "核对 Rect Softness 与 Falloff。",
    route: `/?artifact=${inspectorFixtureArtifactKey}`,
    viewport: compact,
    actions: inspectorFixtureSelection("shapeSoftMaskRect", "ShapeSoftMask"),
    target: componentTarget("ShapeSoftMask", "Shape Soft Mask"),
    workspace: "inspectorFixture",
    componentType: "ShapeSoftMask",
    stateId: "rect",
  },
  {
    id: "shape-soft-mask-rounded",
    title: "Shape Soft Mask / Rounded Rect",
    description: "核对 Rounded Rect 的 Softness 与 Corner Radius。",
    route: `/?artifact=${inspectorFixtureArtifactKey}`,
    viewport: compact,
    actions: inspectorFixtureSelection("shapeSoftMaskRounded", "ShapeSoftMask"),
    target: componentTarget("ShapeSoftMask", "Shape Soft Mask"),
    workspace: "inspectorFixture",
    componentType: "ShapeSoftMask",
    stateId: "rounded-rect",
  },
  {
    id: "shape-soft-mask-circle",
    title: "Shape Soft Mask / Circle",
    description: "核对当前 MiniMap 使用的 Circle 与 Radial Softness。",
    route: `/?artifact=${inspectorFixtureArtifactKey}`,
    viewport: compact,
    actions: inspectorFixtureSelection("shapeSoftMaskCircle", "ShapeSoftMask"),
    target: componentTarget("ShapeSoftMask", "Shape Soft Mask"),
    workspace: "inspectorFixture",
    componentType: "ShapeSoftMask",
    stateId: "circle",
  },
  {
    id: "shape-soft-mask-use-site-override",
    title: "Shape Soft Mask / Use-site Override",
    description: "核对继承 Shape Soft Mask 的 Radial Softness 覆写。",
    route: `/?artifact=${inspectorTextOverrideArtifactKey}`,
    viewport: compact,
    actions: inspectorOverrideSelection("inheritedShapeSoftMask", "ShapeSoftMask"),
    target: componentTarget("ShapeSoftMask", "Shape Soft Mask"),
    workspace: "inspectorFixture",
    componentType: "ShapeSoftMask",
    stateId: "use-site-override",
  },
  ...interactionInspectorCases,
  ...layoutInspectorCases,
  ...customComponentInspectorCases,
  ...resourceStructureInspectorCases,
];
