export { type BenchmarkMeasure, type BenchmarkOptions, type BenchmarkReport, benchmarkWorkspace } from "./app/benchmark.js";
export { type AppManifest, createAppManifest } from "./app/manifest.js";
export {
	type AppBootstrap,
	type BuildWorkspaceOptions,
	type BuildWorkspaceResult,
	createStaticDataService,
	type ExecutePlanOptions,
	type ExecutePlanResult,
	type FieldProvenance,
	type FormatWorkspaceOptions,
	type FormatWorkspaceResult,
	type GridCategoryEntry,
	type GridCell,
	type GridColumn,
	type GridRow,
	type GridTableEntry,
	type GridViewOptions,
	type GridViewResult,
	type ListRecordsOptions,
	type LookupIndex,
	type LookupOption,
	type LookupTableIndex,
	type RecordBatchUpdateRequest,
	type RecordCreateRequest,
	type RecordDetail,
	type RecordListEntry,
	type RecordListResult,
	type RecordReference,
	type RecordReferrersResult,
	type RecordUpdateRequest,
	type RefIndexReference,
	type RefIndexReferrer,
	type ReviewWorkspaceOptions,
	type ReviewWorkspaceResult,
	StaticDataService,
	summarizeVerifyIssues,
	type WorkspaceSearchOptions,
	type WorkspaceSearchResult,
	type WorkspaceSelection,
} from "./app/service.js";
export {
	createV0Boundaries,
	V0_NON_GOALS,
	V0_PROFILES,
	type V0Boundaries,
	type V0NonGoal,
	type V0Profile,
} from "./app/v0-boundaries.js";
export {
	assertWorkspaceRevision,
	createDefaultWorkspaceFileDiff,
	createEmptyWorkspaceFileDiff,
	defaultWorkspaceBackend,
	isWorkspaceRevisionConflictError,
	SCHEMA_FIELD_MUTATION_UNSUPPORTED_CODE,
	SchemaFieldMutationUnsupportedError,
	type StaticDataWorkspaceBackend,
	WORKSPACE_REVISION_CONFLICT_CODE,
	type WorkspaceFileDiff,
	type WorkspaceFileDiffRequest,
	WorkspaceRevisionConflictError,
	type WorkspaceWriteRequest,
} from "./app/workspace-backend.js";
export type {
	WorkspaceSearchEntry,
	WorkspaceSearchMatch,
	WorkspaceSearchScalar,
} from "./app/workspace-search.js";
export {
	createDerivationRuleRegistry,
	type DerivationDependency,
	type DerivationIssue,
	type DerivationOutput,
	type DerivationPatch,
	type DerivationResult,
	type DerivationRule,
	type DerivationRuleContext,
	type DerivationRuleRegistry,
	type DerivedFieldProvenance,
	deriveWorkspace,
	emptyDerivationRegistry,
	getDerivationDownstreamTables,
	getDerivationRelatedTables,
} from "./core/derivation.js";
export {
	applyPlan,
	describePlan,
	type MigrationOperation,
	normalizePlan,
	type Plan,
	type PlanDescription,
	type RecordLocator,
	type RecordTarget,
} from "./core/plan.js";
export {
	createRefIndex,
	createRefIndexForWorkspaceRoot,
	getRecordReferences,
	getRecordReferrers,
	listRefCandidates,
	type RefIndex,
	type RefIndexCandidateTable,
	type RefIndexForwardEntry,
	type RefIndexRecord,
	type RefIndexReverseEntry,
} from "./core/ref-index.js";
export {
	canonicalizeResolvedWorkspace,
	createReviewArtifacts,
	createSemanticDiff,
	DEFAULT_REVIEW_SAMPLE_LIMIT,
	type FieldChange,
	type RefImpact,
	type ResourceImpact,
	type ReviewArtifactOptions,
	type ReviewArtifacts,
	type ReviewSampleBucket,
	type ReviewSummary,
	type SemanticDiff,
	type TableReviewSummary,
} from "./core/review.js";
export {
	RuntimeCatalog,
	type RuntimeId,
	type RuntimePrewarmSummary,
} from "./core/runtime.js";
export {
	type CategoryIR,
	createSchemaCatalog,
	createSchemaIR,
	createWriterContract,
	type FieldIR,
	type ObjectFieldIR,
	type SchemaCatalog,
	type SchemaCatalogCategory,
	type SchemaCatalogSidecar,
	type SchemaCatalogTable,
	type SchemaIR,
	type TableIR,
	type WriterContract,
} from "./core/schema-ir.js";
export { assertValid, type ValidationOptions, type ValidationReport, validateWorkspace } from "./core/validate.js";
export {
	DEFAULT_VERIFY_TARGETS,
	type VerifyIssue,
	type VerifyOptions,
	type VerifyReport,
	type VerifyTarget,
	type VerifyTargetSummary,
	verifyWorkspace,
} from "./core/verify.js";
export {
	buildArtifacts,
	type CategoryWorkspace,
	compileWorkspaceTemplates,
	getCategoryRecordOrder,
	loadWorkspace,
	materializeRecordWithSchema,
	type ResolvedWorkspace,
	resolveWorkspace,
	type Workspace,
	writeBuildArtifacts,
	writeWorkspace,
} from "./core/workspace.js";
export {
	createMcpToolCatalog,
	formatToolError,
	formatToolResult,
	type McpToolCatalogOptions,
	type StaticDataMcpTool,
} from "./mcp/tools.js";
export type { CategoryName, TableName } from "./schema-types.js";
export { registry } from "./schemas.js";
export { createWebRequestHandler, type StartedWebServer, startWebServer, type WebServerOptions } from "./web.js";
